version: '3'

services:
  paginadeds:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://contenedor_db2:3306/paginads?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASS: root
    restart: always
    depends_on:
      contenedor_db2:
        condition: service_healthy

        
  contenedor_db2:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: paginads
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10